---
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Deploy automatic upgrades config
  ansible.builtin.template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"

- name: Start and enable unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    state: started
    enabled: true